const permissionsList = [
  "USER_VIEW",
  "USER_LIST",
  "USER_CHANGE_PASSWORD",
  "USER_UPLOAD_AVATAR",

  "ROLE_CREATE",
  "PERMISSION_VIEW",

  "RELATIONSHIP_LIST_FOLLOWING",
  "RELATIONSHIP_LIST_FOLLOWERS",
  "RELATIONSHIP_VIEW",
  "RELATIONSHIP_FOLLOW",
  "RELATIONSHIP_UNFOLLOW",
  "RELATIONSHIP_BLOCK",
  "RELATIONSHIP_UNBLOCK",

  "CATEGORY_CREATE",
  "CATEGORY_UPDATE",
  "CATEGORY_LIST",
  "CATEGORY_DELETE",
  "CATEGORY_VIEW",
  "CATEGORY_SOFT_DELETE",
  "CATEGORY_HARD_DELETE",
  "CATEGORY_RESTORE",
];

export default permissionsList;