const permissionsList = [
  "USER_VIEW",
  "USER_LIST",
  "USER_CHANGE_PASSWORD",
  "USER_UPLOAD_AVATAR",
  "USER_LIST_FOLLOWING",
  "USER_LIST_FOLLOWERS",
  "USER_CREATE_FOLLOW",
  "USER_VIEW_RELATIONSHIP",
  "USER_UNFOLLOW",
  "USER_CREATE_BLOCK",
  "USER_UNBLOCK",
  "ROLE_CREATE",
  "PERMISSION_VIEW",

  "CATEGORY_CREATE",
  "CATEGORY_UPDATE",
  "CATEGORY_LIST",
  "CATEGORY_DELETE",
  "CATEGORY_VIEW",
  "CATEGORY_SOFT_DELETE",
  "CATEGORY_HARD_DELETE",
  "CATEGORY_RESTORE",
];

export default permissionsList;